// Generated by delombok at Mon Mar 10 08:01:35 CST 2014
package com.toopher.integrations.cas.web.flow;

import com.toopher.integrations.cas.authentication.LevelOfAssurance;
import org.jasig.cas.authentication.principal.Principal;
import java.util.Map;

public class SimplePrincipalLoaResolver implements PrincipalLoaResolver {

    Map<Object, Object> principalLoaDefinitions;

    @Override
    public LevelOfAssurance getLoa(Principal principal) {
        if (principalLoaDefinitions.containsKey(principal.getId())) {
            return (LevelOfAssurance)principalLoaDefinitions.get(principal.getId());
        } else {
            return null;
        }
    }

    @java.lang.SuppressWarnings("all")
    public Map<Object, Object> getPrincipalLoaDefinitions() {
        return this.principalLoaDefinitions;
    }

    @java.lang.SuppressWarnings("all")
    public void setPrincipalLoaDefinitions(final Map<Object, Object> principalLoaDefinitions) {
        this.principalLoaDefinitions = principalLoaDefinitions;
    }
}