// Generated by delombok at Mon Mar 10 08:01:35 CST 2014
package com.toopher.integrations.cas.authentication.principal;

import java.util.Map;

/**
 * Created by drew on 2/27/14.
 */
public class SimpleUsernameToEmailMapper implements UsernameToEmailMapper {

    private String defaultEmailDomain;
    private Map<Object, Object> userDefinitions;

    @Override
    public String getEmailForUsername(String username) {
        if (userDefinitions != null) {
            if (userDefinitions.containsKey(username)) {
                return userDefinitions.get(username).toString();
            }
        }
        if (defaultEmailDomain != null) {
            return username + "@" + defaultEmailDomain;
        }
        return "unknown";
    }

    @java.lang.SuppressWarnings("all")
    public String getDefaultEmailDomain() {
        return this.defaultEmailDomain;
    }

    @java.lang.SuppressWarnings("all")
    public void setDefaultEmailDomain(final String defaultEmailDomain) {
        this.defaultEmailDomain = defaultEmailDomain;
    }

    @java.lang.SuppressWarnings("all")
    public Map<Object, Object> getUserDefinitions() {
        return this.userDefinitions;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserDefinitions(final Map<Object, Object> userDefinitions) {
        this.userDefinitions = userDefinitions;
    }
}