// Generated by delombok at Mon Mar 10 08:01:35 CST 2014
package com.toopher.integrations.cas.authentication.principal;

import com.toopher.integrations.cas.ToopherConfig;
import org.jasig.cas.authentication.principal.Credentials;
import org.jasig.cas.authentication.principal.CredentialsToPrincipalResolver;
import org.jasig.cas.authentication.principal.Principal;
import org.jasig.cas.authentication.principal.SimplePrincipal;
import org.apache.log4j.Logger;
import org.slf4j.LoggerFactory;

public class ToopherCredentialsToPrincipalResolver implements CredentialsToPrincipalResolver {

    private org.slf4j.Logger logger = LoggerFactory.getLogger(this.getClass());
    private ToopherConfig toopherConfig;

    @Override
    public Principal resolvePrincipal(Credentials credentials) {
        logger.debug("ToopherCredentialsToPrincipalResolver: resolvePrincipal");
        final ToopherCredentials toopherCredentials = (ToopherCredentials)credentials;
        SimplePrincipal simplePrincipal = new SimplePrincipal(toopherCredentials.getUsername());
        return simplePrincipal;
    }

    @Override
    public boolean supports(Credentials credentials) {
        return (credentials.getClass() == ToopherCredentials.class);
    }

    @java.lang.SuppressWarnings("all")
    public ToopherConfig getToopherConfig() {
        return this.toopherConfig;
    }

    @java.lang.SuppressWarnings("all")
    public void setToopherConfig(final ToopherConfig toopherConfig) {
        this.toopherConfig = toopherConfig;
    }
}
