// Generated by delombok at Mon Mar 10 08:01:35 CST 2014
package com.toopher.integrations.cas.authentication.principal;

import java.util.Map;
import org.jasig.cas.authentication.principal.Credentials;

public class ToopherCredentials implements Credentials {

    private static final long serialVersionUID = 0L;
    private Map<String, String> requestParameters;
    private String loginTicketId;
    private String username;

    public boolean getChallengeRequired() {
        if (requestParameters.containsKey("challenge_required")) {
            return requestParameters.get("challenge_required").toLowerCase().equals("true");
        } else {
            return false;
        }
    }

    public boolean getAutomated() {
        if (requestParameters.containsKey("automated")) {
            return requestParameters.get("automated").toLowerCase().equals("true");
        } else {
            return false;
        }
    }

    @java.lang.SuppressWarnings("all")
    public Map<String, String> getRequestParameters() {
        return this.requestParameters;
    }

    @java.lang.SuppressWarnings("all")
    public void setRequestParameters(final Map<String, String> requestParameters) {
        this.requestParameters = requestParameters;
    }

    @java.lang.SuppressWarnings("all")
    public String getLoginTicketId() {
        return this.loginTicketId;
    }

    @java.lang.SuppressWarnings("all")
    public void setLoginTicketId(final String loginTicketId) {
        this.loginTicketId = loginTicketId;
    }

    @java.lang.SuppressWarnings("all")
    public String getUsername() {
        return this.username;
    }

    @java.lang.SuppressWarnings("all")
    public void setUsername(final String username) {
        this.username = username;
    }
}