// Generated by delombok at Mon Mar 10 08:01:35 CST 2014
package com.toopher.integrations.cas.authentication;

import java.io.Serializable;

public class LevelOfAssurance implements Serializable {
    private static final long serialVersionUID = 0;
    public static final String LOA_ATTRIBUTE_NAME = "TOOPHER_AUTHENTICATION_LOA";
    public static final String LOA_USERNAME_PASSWORD = "username_password";
    public static final String LOA_TOOPHER = "toopher";
    public static final String LOA_TOOPHER_DISALLOW_AUTOMATION = "disallow_automation";
    public static final String LOA_TOOPHER_REQUIRE_CHALLENGE = "require_challenge";
    public static final Long LOA_USERNAME_PASSWORD_VAL = 2L;
    public static final Long LOA_TOOPHER_VAL = 4L;
    public static final Long LOA_TOOPHER_DISALLOW_AUTOMATION_VAL = 8L;
    public static final Long LOA_TOOPHER_REQUIRE_CHALLENGE_VAL = 16L;
    private boolean usernamePasswordRequired;
    private boolean toopherRequired;
    private boolean disallowAutomationRequired;
    private boolean challengeRequired;

    public LevelOfAssurance() {
        usernamePasswordRequired = true;
        toopherRequired = false;
        disallowAutomationRequired = false;
        challengeRequired = false;
    }

    public LevelOfAssurance(Long loaValue) {
        usernamePasswordRequired = (loaValue & LOA_USERNAME_PASSWORD_VAL) != 0;
        toopherRequired = (loaValue & LOA_TOOPHER_VAL) != 0;
        disallowAutomationRequired = (loaValue & LOA_TOOPHER_DISALLOW_AUTOMATION_VAL) != 0;
        challengeRequired = (loaValue & LOA_TOOPHER_REQUIRE_CHALLENGE_VAL) != 0;
    }

    public Long asLong() {
        Long result = 0L;
        if (usernamePasswordRequired) {
            result = result | LOA_USERNAME_PASSWORD_VAL;
        }
        if (toopherRequired) {
            result = result | LOA_TOOPHER_VAL;
        }
        if (disallowAutomationRequired) {
            result = result | LOA_TOOPHER_DISALLOW_AUTOMATION_VAL;
        }
        if (challengeRequired) {
            result = result | LOA_TOOPHER_REQUIRE_CHALLENGE_VAL;
        }
        return result;
    }

    public String asString() {
        String result = "";
        if (usernamePasswordRequired) {
            result = result + "|" + LOA_USERNAME_PASSWORD;
        }
        if (toopherRequired) {
            result = result + "|" + LOA_TOOPHER;
        }
        if (disallowAutomationRequired) {
            result = result + "|" + LOA_TOOPHER_DISALLOW_AUTOMATION;
        }
        if (challengeRequired) {
            result = result + "|" + LOA_TOOPHER_REQUIRE_CHALLENGE;
        }
        return result + "|";
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof LevelOfAssurance)) return false;
        final LevelOfAssurance other = (LevelOfAssurance)o;
        if (!other.canEqual((java.lang.Object)this)) return false;
        if (this.isUsernamePasswordRequired() != other.isUsernamePasswordRequired()) return false;
        if (this.isToopherRequired() != other.isToopherRequired()) return false;
        if (this.isDisallowAutomationRequired() != other.isDisallowAutomationRequired()) return false;
        if (this.isChallengeRequired() != other.isChallengeRequired()) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    public boolean canEqual(final java.lang.Object other) {
        return other instanceof LevelOfAssurance;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 277;
        int result = 1;
        result = result * PRIME + (this.isUsernamePasswordRequired() ? 2609 : 2591);
        result = result * PRIME + (this.isToopherRequired() ? 2609 : 2591);
        result = result * PRIME + (this.isDisallowAutomationRequired() ? 2609 : 2591);
        result = result * PRIME + (this.isChallengeRequired() ? 2609 : 2591);
        return result;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isUsernamePasswordRequired() {
        return this.usernamePasswordRequired;
    }

    @java.lang.SuppressWarnings("all")
    public void setUsernamePasswordRequired(final boolean usernamePasswordRequired) {
        this.usernamePasswordRequired = usernamePasswordRequired;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isToopherRequired() {
        return this.toopherRequired;
    }

    @java.lang.SuppressWarnings("all")
    public void setToopherRequired(final boolean toopherRequired) {
        this.toopherRequired = toopherRequired;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isDisallowAutomationRequired() {
        return this.disallowAutomationRequired;
    }

    @java.lang.SuppressWarnings("all")
    public void setDisallowAutomationRequired(final boolean disallowAutomationRequired) {
        this.disallowAutomationRequired = disallowAutomationRequired;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isChallengeRequired() {
        return this.challengeRequired;
    }

    @java.lang.SuppressWarnings("all")
    public void setChallengeRequired(final boolean challengeRequired) {
        this.challengeRequired = challengeRequired;
    }
}