// Generated by delombok at Mon Mar 10 08:01:35 CST 2014
package com.toopher.integrations.cas;

/**
 * Bean to store ToopherAPI configuration data
 * <p>
 * example configuration, taking configuration values from environment variables:
 * </p>
 * <pre>
 * {@code <bean id="toopherConfig" class="com.toopher.integrations.cas.ToopherConfig">
 * <property name="consumerKey" value="${TOOPHER_CONSUMER_KEY}"/>
 * <property name="consumerSecret" value="${TOOPHER_CONSUMER_SECRET}"/>
 * <property name="apiUrl" value="${TOOPHER_BASE_URL}"/>
 * </bean>
 * }
 * </pre>
 *
 * @author Drew Shafer <drew@toopher.com>
 * @version 1.0
 * @see <a href="https://dev.toopher.com/docs">ToopherAPI Developer Docs</a>
 */
public class ToopherConfig {

    private String consumerKey;
    private String consumerSecret;
    private String apiUrl;

    @java.lang.SuppressWarnings("all")
    public String getConsumerKey() {
        return this.consumerKey;
    }

    @java.lang.SuppressWarnings("all")
    public void setConsumerKey(final String consumerKey) {
        this.consumerKey = consumerKey;
    }

    @java.lang.SuppressWarnings("all")
    public String getConsumerSecret() {
        return this.consumerSecret;
    }

    @java.lang.SuppressWarnings("all")
    public void setConsumerSecret(final String consumerSecret) {
        this.consumerSecret = consumerSecret;
    }

    @java.lang.SuppressWarnings("all")
    public String getApiUrl() {
        return this.apiUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setApiUrl(final String apiUrl) {
        this.apiUrl = apiUrl;
    }
}