// Generated by delombok at Mon Mar 10 08:01:35 CST 2014
package com.toopher.integrations.cas;

/**
 * Bean to store ToopherAPI configuration data.
 *
 * @author Drew Shafer <drew@toopher.com>
 * @version 1.0
 * @see <a href="https://dev.toopher.com/docs">ToopherAPI Developer Docs</a>
 */
public class ToopherConfig {

    private final String consumerKey;
    private final String consumerSecret;
    private final String apiUrl;

    public ToopherConfig(final String consumerKey, final String consumerSecret, final String apiUrl) {
        this.consumerKey = consumerKey;
        this.consumerSecret = consumerSecret;
        this.apiUrl = apiUrl;
    }

    public String getConsumerKey() {
        return this.consumerKey;
    }

    public String getConsumerSecret() {
        return this.consumerSecret;
    }

    public String getApiUrl() {
        return this.apiUrl;
    }

}
